###
GET http://localhost:3000/api/refresh HTTP/1.1

###
GET http://localhost:3000/api/logout HTTP/1.1

###
GET http://localhost:3000/api/users HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjc4Nzk1ODE4LCJleHAiOjE2Nzg3OTU4NDh9.ZrEEKRTyU5lH7mzJapGQryfksawMev8kub0kXgFl9HI

###
POST http://localhost:3000/api/auth/register HTTP/1.1
content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}
###

POST http://localhost:3000/api/auth/login HTTP/1.1
content-Type: application/json

{
    "username": "admin",
    "password":"admin"
}